version: 2

jobs:

  build:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run: sudo apt-get update -y && sudo apt-get install cmake libpq-dev -y
      - run: cargo build --release --features all

  test-mem:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run: sudo apt-get update -y && sudo apt-get install cmake libpq-dev -y
      - run: cargo test --features all

  test-postgres:
    docker:
      - image: circleci/rust:latest
        environment:
          DATABASE_URL: postgres://root@localhost/dytp_test
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: dytp_test
    steps:
      - checkout
      - run: sudo apt-get update -y && sudo apt-get install cmake libpq-dev -y
      - run: cargo install diesel_cli
      - run: diesel migration run
      - run: cargo test --features all

workflows:
  version: 2

  pull_request:
    jobs:
      - build
      - test-mem
      - test-postgres
