[package]
name = "dytp-protocol"
version = "0.1.0"
authors = ["taicsuzu <taichiro0709@gmail.com>"]
edition = "2018"

[dependencies]
dytp-component = { path = "../dytp-component" }
bytes = "*"
regex = "*"
semver = "*"